title: Ryan Amundson # your name (or website title) here
logo: "/images/ryan_profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Engineer 
  <br><br>
  Passionate about software craftsmanship, machine learning, and AI with a strong focus on continuous learning and delivery. Deep technical knowledge of large scale distributed systems, machine learning, operations and both real-time and batch data processing. 
  <br><br>
  <a href="https://www.linkedin.com/in/ryanamundson1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
